http:
  port: "8081"

sftp:
  host: "sftp.px.bylinkr.com"
  port: "8422"
  user: "linkr"
  password: "![1Q/EViuP4xrWHl/PnYWOJQ==]"
  working-directory: "upload/theu"
  personal-directory: "Mamy"
  invoices-file: "invoices.json"
  hoinaco-file: "hoinaco.csv"
  absences-file: "Absences.csv"
  product-file: "Prod/products.csv"