#%RAML 1.0 Trait
responses:  
  500:
    body:
      application/json:
        type: standardError
        example:
          correlationId: fe5zef1-194b-475c-8dee-0zef56zf4180
          statusCode: 500
          namespace: APIKIT
          identifier: INTERNAL_SERVER_ERROR
          description: Something went wrong