#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        type: standardError
        example:
          correlationId: fe5zef1-194b-475c-8dee-0zef56zf4180
          statusCode: 400
          namespace: APIKIT
          identifier: BAD_REQUEST
          description: Field xxx is missing